# Generated by Django 3.2 on 2021-04-22 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=32, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=32, verbose_name='Last Name')),
                ('type', models.CharField(choices=[('UA', 'Undergraduate Assistant'), ('RA', 'Research Assistant')], max_length=32, verbose_name='Type of Employment')),
                ('capacity', models.FloatField(default=1.0, verbose_name='Capacity')),
                ('hiring_date', models.DateField(verbose_name='Hiring Date')),
                ('expiration_date', models.DateField(verbose_name='Expiration Date')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Titel')),
                ('description', models.CharField(max_length=2400, verbose_name='Beschreibung')),
            ],
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erpapp.task')),
                ('rotation', models.CharField(choices=[('ST', 'Sommer Term'), ('WT', 'Winter Term'), ('ET', 'Every Term'), ('irreg', 'irregular')], default='Every Term', max_length=16, verbose_name='Term')),
                ('requirement', models.FloatField(default=1, verbose_name='Requirement')),
            ],
            bases=('erpapp.task',),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erpapp.task')),
                ('ressources', models.FloatField(verbose_name='Ressources')),
            ],
            bases=('erpapp.task',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erpapp.task')),
                ('ressources', models.FloatField(verbose_name='Ressources')),
                ('begin', models.DateField(verbose_name='Project Start')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('end', models.DateField(verbose_name='Project End')),
            ],
            bases=('erpapp.task',),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='From')),
                ('end', models.DateField(verbose_name='To')),
                ('percentage', models.FloatField(verbose_name='Functional Capacity')),
                ('responsibility', models.BooleanField(default=False, verbose_name='Responsible')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpapp.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpapp.task')),
            ],
        ),
    ]
