# Generated by Django 3.2 on 2021-04-30 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentOnMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='From')),
                ('end', models.DateField(verbose_name='To')),
                ('percentage', models.FloatField(verbose_name='Functional Capacity')),
                ('responsibility', models.BooleanField(default=False, verbose_name='Responsible')),
            ],
            options={
                'db_table': 'assignment_on_month',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=32, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=32, verbose_name='Last Name')),
                ('type', models.CharField(choices=[('Undergraduate Assistant', 'Undergraduate Assistant'), ('Research Assistant', 'Research Assistant')], max_length=32, verbose_name='Type of Employment')),
                ('capacity', models.FloatField(default=1.0, verbose_name='Capacity')),
                ('hiring_date', models.DateField(verbose_name='Hiring Date')),
                ('months_hired', models.FloatField(default=6.0, verbose_name='Months hired')),
                ('expiration_date', models.DateField(verbose_name='Expiration Date')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='MonthYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=50, verbose_name='Title')),
                ('description', models.CharField(default='Describe the task!', max_length=2400, verbose_name='description')),
                ('assigned_employees_on_month', models.ManyToManyField(through='erpapp.AssignmentOnMonth', to='erpapp.Employee')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erpapp.task')),
                ('rotation', models.CharField(choices=[('Summer Term', 'Summer Term'), ('Winter Term', 'Winter Term'), ('Every Term', 'Every Term'), ('Irregular', 'irregular')], default='Every Term', max_length=16, verbose_name='Term')),
                ('requirement', models.FloatField(default=1, verbose_name='Requirement')),
            ],
            options={
                'db_table': 'chair',
            },
            bases=('erpapp.task',),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erpapp.task')),
                ('ressources', models.FloatField(verbose_name='Ressources')),
            ],
            options={
                'db_table': 'position',
            },
            bases=('erpapp.task',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erpapp.task')),
                ('ressources', models.FloatField(verbose_name='Ressources')),
                ('begin', models.DateField(verbose_name='Project Start')),
                ('duration', models.FloatField(verbose_name='Duration (in months)')),
                ('end', models.DateField(verbose_name='Project End')),
            ],
            options={
                'db_table': 'project',
            },
            bases=('erpapp.task',),
        ),
        migrations.AddField(
            model_name='assignmentonmonth',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpapp.employee'),
        ),
        migrations.AddField(
            model_name='assignmentonmonth',
            name='month_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpapp.monthyear'),
        ),
        migrations.AddField(
            model_name='assignmentonmonth',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpapp.task'),
        ),
    ]
