# Generated by Django 3.2 on 2021-05-03 21:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentPerMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(verbose_name='Duration (in months)')),
                ('percentage', models.FloatField(default=0.2, verbose_name='Functional Capacity')),
                ('responsibility', models.BooleanField(default=False, verbose_name='Responsible')),
            ],
            options={
                'db_table': 'assignment_per_month',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=32, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=32, verbose_name='Last Name')),
                ('type', models.CharField(choices=[('Undergraduate Assistant', 'Undergraduate Assistant'), ('Research Assistant', 'Research Assistant')], max_length=32, verbose_name='Type of Employment')),
                ('capacity', models.FloatField(default=1.0, verbose_name='Capacity')),
                ('hiring_date', models.DateField(verbose_name='Hiring Date')),
                ('expiration_date', models.DateField(verbose_name='Expiration Date')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10)),
                ('year', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='2021', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=50, verbose_name='Title')),
                ('description', models.CharField(default='Describe the task!', max_length=2400, verbose_name='description')),
                ('assigned_employees_on_month', models.ManyToManyField(through='erpapp.AssignmentPerMonth', to='erpapp.Employee')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erpapp.task')),
                ('rotation', models.CharField(choices=[('Summer Term', 'Summer Term'), ('Winter Term', 'Winter Term'), ('Every Term', 'Every Term'), ('Irregular', 'irregular')], default='Every Term', max_length=16, verbose_name='Term')),
                ('requirement', models.FloatField(default=1, verbose_name='Requirement')),
            ],
            options={
                'db_table': 'chair',
            },
            bases=('erpapp.task',),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erpapp.task')),
                ('ressources', models.FloatField(verbose_name='Ressources')),
            ],
            options={
                'db_table': 'position',
            },
            bases=('erpapp.task',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erpapp.task')),
                ('ressources', models.FloatField(verbose_name='Ressources')),
                ('begin', models.DateField(verbose_name='Project Start')),
                ('end', models.DateField(verbose_name='Project End')),
            ],
            options={
                'db_table': 'project',
            },
            bases=('erpapp.task',),
        ),
        migrations.AddField(
            model_name='assignmentpermonth',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpapp.employee'),
        ),
        migrations.AddField(
            model_name='assignmentpermonth',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpapp.month'),
        ),
        migrations.AddField(
            model_name='assignmentpermonth',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpapp.task'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(default=datetime.datetime(2021, 5, 3, 21, 9, 49, 853261, tzinfo=utc), verbose_name='From')),
                ('end', models.DateField(default=datetime.datetime(2021, 5, 3, 21, 9, 49, 853261, tzinfo=utc), verbose_name='To')),
                ('percentage', models.FloatField(default=0.2, verbose_name='Functional Capacity')),
                ('responsibility', models.BooleanField(default=False, verbose_name='Responsible')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpapp.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpapp.task')),
            ],
            options={
                'db_table': 'assignment',
            },
        ),
    ]
