# Generated by Django 3.2 on 2021-05-10 17:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('erpapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='comment',
            field=models.CharField(default='', max_length=2400, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='end',
            field=models.DateField(default=datetime.datetime(2021, 5, 10, 17, 49, 24, 710998, tzinfo=utc), verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='start',
            field=models.DateField(default=datetime.datetime(2021, 5, 10, 17, 49, 24, 710998, tzinfo=utc), verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default='Describe the task!', max_length=2400, verbose_name='Description'),
        ),
    ]
