# Generated by Django 3.2 on 2021-04-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthyear',
            name='date',
        ),
        migrations.AddField(
            model_name='monthyear',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='December', max_length=10),
            preserve_default=False,
        ),
    ]
