# Generated by Django 3.2 on 2021-05-03 15:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('erpapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='duration',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='end',
            field=models.DateField(default=datetime.datetime(2021, 5, 3, 15, 12, 15, 137760, tzinfo=utc), verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='start',
            field=models.DateField(default=datetime.datetime(2021, 5, 3, 15, 12, 15, 137760, tzinfo=utc), verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='assignmentpermonth',
            name='duration',
            field=models.IntegerField(verbose_name='Duration (in months)'),
        ),
    ]
