# Generated by Django 3.2 on 2021-05-01 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='end',
            field=models.DateField(default=datetime.datetime(2021, 5, 1, 18, 34, 15, 277879), verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='start',
            field=models.DateField(default=datetime.datetime(2021, 5, 1, 18, 34, 15, 277879), verbose_name='From'),
        ),
        migrations.AlterModelTable(
            name='assignment',
            table='assignment',
        ),
    ]
