# Generated by Django 3.2 on 2021-04-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpapp', '0002_auto_20210430_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthyear',
            name='year',
            field=models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='2020', max_length=5),
            preserve_default=False,
        ),
    ]
