# Generated by Django 3.2 on 2021-04-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpapp', '0003_monthyear_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentonmonth',
            name='end',
        ),
        migrations.RemoveField(
            model_name='assignmentonmonth',
            name='start',
        ),
        migrations.AddField(
            model_name='assignmentonmonth',
            name='duration',
            field=models.IntegerField(default=3, verbose_name='Duration (in months)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monthyear',
            name='year',
            field=models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='2021', max_length=5),
        ),
    ]
