# Generated by Django 3.2 on 2021-04-30 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erpapp', '0005_auto_20210430_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentPerMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=0, verbose_name='Duration (in months)')),
                ('percentage', models.FloatField(default=0.2, verbose_name='Functional Capacity')),
                ('responsibility', models.BooleanField(default=False, verbose_name='Responsible')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpapp.employee')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpapp.month')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpapp.task')),
            ],
            options={
                'db_table': 'assignment_per_month',
            },
        ),
        migrations.DeleteModel(
            name='AssignmentOnMonth',
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_employees_on_month',
            field=models.ManyToManyField(through='erpapp.AssignmentPerMonth', to='erpapp.Employee'),
        ),
    ]
