# Generated by Django 3.2 on 2021-04-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erpapp', '0006_auto_20210430_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='months_hired',
        ),
    ]
